site_name: 3Dwork Klipper Wizard
site_description: El asistente más fácil para configurar Klipper en tu impresora 3D
site_url: https://3dwork-io.github.io/3dwork-klipper/
site_author: 3Dwork
copyright: © 2024 3Dwork

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Modo oscuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate

nav:
  - Home: index.md
  - Instalación: instalacion.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang: es